// Nerds Against Humanity — Full Card Deck
// Original cards from the spreadsheet + generated cards to fill out the deck

export const blackCards = [
  // ============================================================
  // ORIGINAL BLACK CARDS (from the spreadsheet)
  // ============================================================
  { text: "New at McDonald's - The Morning Mc_____ !", pick: 1 },
  { text: "The secret ingredient in McDonald's hash browns is _____.", pick: 1 },
  { text: "What Spuds MacKenzie is doing RIGHT now.", pick: 1 },
  { text: "Sorry I'm late for work. I was just _____.", pick: 1 },
  { text: "What's that buzzing sound?", pick: 1 },
  { text: "Tinky Winky carries _____ in his man-purse.", pick: 1 },
  { text: "\"Everybody get up, it's time to slam now. We got a real jam going down. Welcome to the _____\"", pick: 1 },
  { text: "\"Weird, I just got an email from a Nigerian prince saying he'll give me _____ if I send him _____\"", pick: 2 },
  { text: "\"It's rainin' men... Hallelujah, it's rainin' _____\"", pick: 1 },
  { text: "Little known Star Wars fact: Yoda would often use the Force to _____ when he was bored.", pick: 1 },
  { text: "_____. That's what they used to call me back in kindergarten.", pick: 1 },
  { text: "\"If you can't love yourself, how in the hell are you supposed to love _____? Can I get an amen?!\"", pick: 1 },
  { text: "What they should shoot out of confetti cannons at child beauty pageants.", pick: 1 },
  { text: "The worst line of Happy Meal toys.", pick: 1 },
  { text: "Rudolph the Red-Nosed _____", pick: 1 },
  { text: "\"In the gay community, there are Bears, Otters, Twinks and _____\"", pick: 1 },
  { text: "\"Our Father, who art in Heaven. Hallowed be thy _____\"", pick: 1 },
  { text: "\"Don't cry over spilled milk... Instead, cry over _____\"", pick: 1 },
  { text: "\"This Summer, Gandalf returns as he and the Hobbits do battle with _____\"", pick: 1 },
  { text: "Toy Story 4: Buzz and Woody are _____", pick: 1 },
  { text: "What Mike Dwyer keeps hidden from the world.", pick: 1 },
  { text: "\"Mom, I accidentally caught you and dad _____\"", pick: 1 },
  { text: "\"Girls simply don't like the word 'cunt'. Instead we shall name it _____.\"", pick: 1 },
  { text: "New to Big Rig's menu: _____", pick: 1 },
  { text: "\"Forget the cardboard... These days, breakdancers cut it loose on _____.\"", pick: 1 },
  { text: "Hey Otis... Hold my beer while I _____", pick: 1 },
  { text: "How would I describe Sheila? Hmmm... She's definitely _____", pick: 1 },
  { text: "Why doesn't my mom love me anymore?", pick: 1 },
  { text: "This is my favorite thing to put in my mouth.", pick: 1 },
  { text: "These tears in my eyes aren't from crying... They're from _____", pick: 1 },
  { text: "\"Tonight, in the WWE, Hulk Hogan is set to take on _____ in the Hell in a Cell cage match!!\"", pick: 1 },
  { text: "\"If every time a bell rings, an angel gets its wings, then every time _____, Yan gets _____\"", pick: 2 },
  { text: "\"In prison, Jared Fogel passes time by drawing pictures of _____\"", pick: 1 },
  { text: "\"Don't go too far, chum. I wanna _____\"", pick: 1 },
  { text: "The dowry for my daughter is _____", pick: 1 },
  { text: "_____, that's what society needs right now!", pick: 1 },
  { text: "\"(Sing This:) If you like Pina Coladas, and _____\"", pick: 1 },
  { text: "\"Oh baby, I'm going to rock your world tonight. Get ready for some filthy talking and some _____\"", pick: 1 },
  { text: "Sometimes I'll _____ when I can't sleep at night.", pick: 1 },
  { text: "(Sing This:) Hello darkness my old friend... I've come to _____", pick: 1 },
  { text: "Why does Buckley's taste so bad?", pick: 1 },
  { text: "Before becoming a rock legend Slash would pass the time _____ to make ends meet.", pick: 1 },
  { text: "Why is my face wet?", pick: 1 },
  { text: "Tune in to Making a Murderer: Season 3 where Steven Avery is _____", pick: 1 },
  { text: "\"To turn their season around, the Ottawa Senators tried _____ to boost morale.\"", pick: 1 },
  { text: "The key ingredient to maintaining Donald Trump's hair-do: _____", pick: 1 },
  { text: "I would give _____ for one no-questions-asked night with Henry Cavill.", pick: 1 },
  { text: "\"In an attempt to discover a new thrilling high, Charlie Sheen tried snorting _____.\"", pick: 1 },
  { text: "And the Teen Choice Award for _____ goes to... _____", pick: 2 },
  { text: "\"Download Adele's new single _____, a song about _____. Available on iTunes\"", pick: 2 },
  { text: "\"I didn't have any change on me, so I put _____ in the kids' Unicef boxes\"", pick: 1 },
  { text: "\"Santa gives good kids _____, shitty kids get _____.\"", pick: 2 },
  { text: "(Sing This:) All I want for Christmas is _____.", pick: 1 },
  { text: "_____. Yep, it DOES taste like chicken!!", pick: 1 },
  { text: "\"(Sing This:) When the moon hits your eye like a _____, that's AMORE!!\"", pick: 1 },
  { text: "\"Ottawa Police tech company 'Versaterm' has reduced crime in the Ottawa area with a new technique involving _____\"", pick: 1 },
  { text: "Breaking news, Coronavirus has been cured from _____.", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "And the Academy Award for _____ goes to _____.", pick: 2 },
  { text: "New research has proven that people with _____ are more likely to lead a happier life.", pick: 1 },
  { text: "\"That's right, I killed _____. How you ask? _____\"", pick: 2 },
  { text: "The new Versaterm logo goes back to our roots and will incorporate _____", pick: 1 },
  { text: "I like to hit _____ with _____", pick: 2 },
  { text: "You make me feel like a natural _____", pick: 1 },
  { text: "My perfect date night would start with _____ and end with _____", pick: 2 },
  { text: "I like big _____ and I cannot lie", pick: 1 },
  { text: "Life is like a box of _____", pick: 1 },
  { text: "I'd replace the Versaterm bathroom jokes with _____", pick: 1 },
  { text: "\"Next time we go for sushi, we are not ordering _____\"", pick: 1 },
  { text: "\"The casino night is gonna be lit, I'm gonna _____ in _____\"", pick: 2 },
  { text: "Ivan had _____ delivered to Versaterm", pick: 1 },
  { text: "I saw Laporte put _____ into the coffee maker", pick: 1 },
  { text: "I really admire _____", pick: 1 },
  { text: "\"Sometimes, when I'm lonely, I find myself fantasizing about _____\"", pick: 1 },
  { text: "Many _____ make light work", pick: 1 },
  { text: "You'll catch more _____ with _____ than with vinegar", pick: 2 },
  { text: "Like herding _____", pick: 1 },
  { text: "One man's trash is another man's _____", pick: 1 },
  { text: "There's more than one way to skin a _____", pick: 1 },

  // ============================================================
  // GENERATED BLACK CARDS
  // ============================================================
  { text: "Step right up, ladies and gentlemen! Behind curtain number three is _____!", pick: 1 },
  { text: "What's the one thing you should never Google?", pick: 1 },
  { text: "TSA confiscated _____ from my carry-on.", pick: 1 },
  { text: "What's hiding under The Rock's fanny pack?", pick: 1 },
  { text: "Netflix and _____.", pick: 1 },
  { text: "Welcome to Costco. Today's free sample is _____.", pick: 1 },
  { text: "The real reason the dinosaurs went extinct: _____.", pick: 1 },
  { text: "What does Batman keep in the utility belt that Robin doesn't know about?", pick: 1 },
  { text: "My therapist says I have an unhealthy attachment to _____.", pick: 1 },
  { text: "In a deleted scene from Shrek, Donkey discovers _____.", pick: 1 },
  { text: "The next Marvel movie: Avengers: The Age of _____.", pick: 1 },
  { text: "What's really in Area 51?", pick: 1 },
  { text: "When I die, I want to be buried with _____.", pick: 1 },
  { text: "I got banned from Walmart for _____.", pick: 1 },
  { text: "The secret to a happy marriage is _____ and _____.", pick: 2 },
  { text: "What did the last guy get kicked off the island for on Survivor?", pick: 1 },
  { text: "IKEA's newest product: A DIY _____.", pick: 1 },
  { text: "The number one cause of divorce in 2026: _____.", pick: 1 },
  { text: "What would grandma be shocked to find in your browser history?", pick: 1 },
  { text: "During the zombie apocalypse, my weapon of choice would be _____.", pick: 1 },
  { text: "_____ is a slippery slope that leads to _____.", pick: 2 },
  { text: "What really happens at a Dungeons & Dragons session?", pick: 1 },
  { text: "The worst thing to say during a job interview: _____.", pick: 1 },
  { text: "Florida Man arrested for _____.", pick: 1 },
  { text: "What's the next Olympic sport?", pick: 1 },
  { text: "My safe word is _____.", pick: 1 },
  { text: "And on the eighth day, God created _____.", pick: 1 },
  { text: "_____, the breakfast of champions!", pick: 1 },
  { text: "What keeps Queen Elizabeth's corpse looking so fresh?", pick: 1 },
  { text: "My Tinder bio says I'm really into _____.", pick: 1 },
  { text: "\"What's in the box?! WHAT'S IN THE BOX?! Oh... it's _____.\"", pick: 1 },
  { text: "What was the 11th plague that God decided was too far?", pick: 1 },
  { text: "While everyone was distracted by the Kardashians, the government was secretly _____.", pick: 1 },
  { text: "The worst thing to whisper in someone's ear during a hug: _____.", pick: 1 },
  { text: "\"Dr. Phil's latest episode: 'Help! My teenager is addicted to _____.'\"", pick: 1 },
  { text: "Next on Gordon Ramsay's menu: _____. It's fucking RAW!", pick: 1 },
  { text: "White people love _____. It's basically their religion.", pick: 1 },
  { text: "In the Upside Down, instead of Demogorgons there are _____.", pick: 1 },
  { text: "At Hogwarts, the unforgivable curse they don't teach you about: _____.", pick: 1 },
  { text: "What's the worst thing to bring to a potluck?", pick: 1 },
  { text: "The airline lost my luggage, so now all I have is _____.", pick: 1 },
  { text: "When I'm stressed, I cope by _____.", pick: 1 },
  { text: "My spirit animal is _____.", pick: 1 },
  { text: "The worst prize in a cereal box: _____.", pick: 1 },
  { text: "I got a tattoo of _____ on my _____.", pick: 2 },
  { text: "What would make The Bachelor actually worth watching?", pick: 1 },
  { text: "You haven't lived until you've tried _____ with _____.", pick: 2 },
  { text: "The thing I'm most ashamed to admit I've done at 3 AM: _____.", pick: 1 },
  { text: "What's the first thing aliens would notice about humans?", pick: 1 },
  { text: "The nurse said my blood test came back positive for _____.", pick: 1 },
  { text: "Instead of a midlife crisis, I'm having a midlife _____.", pick: 1 },
  { text: "The worst superhero power: the ability to _____.", pick: 1 },
  { text: "The government is putting _____ in the water supply.", pick: 1 },
  { text: "\"Honey, I can explain! It's not what it looks like, it's just _____.\"", pick: 1 },
  { text: "The true meaning of Christmas is _____.", pick: 1 },
  { text: "Gordon Ramsay just found _____ in the walk-in fridge.", pick: 1 },
  { text: "In Soviet Russia, _____ does YOU.", pick: 1 },
  { text: "During the rapture, I'll be too busy _____ to notice.", pick: 1 },
  { text: "_____: For when thoughts and prayers just aren't enough.", pick: 1 },
  { text: "The real treasure was _____ all along.", pick: 1 },
  { text: "Coming soon to OnlyFans: _____.", pick: 1 },
  { text: "What the tooth fairy REALLY does with all those teeth: _____.", pick: 1 },
  { text: "Elon Musk's next venture: _____.", pick: 1 },
  { text: "The worst thing to yell during a moment of silence: _____.", pick: 1 },
  { text: "Behind every great man, there's _____.", pick: 1 },
  { text: "The real reason I got fired: _____.", pick: 1 },
  { text: "\"Alexa, order me _____.\"", pick: 1 },
  { text: "What I found growing in the office fridge: _____.", pick: 1 },
  { text: "The deleted verse of 'Bohemian Rhapsody' is about _____.", pick: 1 },
  { text: "What they don't tell you about parenthood: _____.", pick: 1 },
];

export const whiteCards = [
  // ============================================================
  // ORIGINAL WHITE CARDS (from the spreadsheet)
  // ============================================================
  "Thinking Barney the Dinosaur is pretty much Grimace, but gayer.",
  "Ronald McDonald's curly red pubes.",
  "A van full of drag queens on their way to a wig sale",
  "Zombie Chihuahuas!!",
  "A human carcass flailing dangerously from a ceiling fan on high speed",
  "A house centipede nesting in your urethra",
  "An old Russian that doesn't wash his hands after peeing",
  "Licking Bill Cosby's pudding pop.",
  "A Cosby Sweater",
  "Donkey Punching a priest",
  "Playing the rusty trombone",
  "Gargling mayonnaise",
  "Cradle the balls, stroke the shaft and swallow the gravy",
  "Vaginal discharge",
  "Using a gloworm as anal beads",
  "He-Man!! AND THE MASTERS OF THE UNIVERSE!!!",
  "Watch me whip... now watch me nay-nay",
  "A dog's firetruck red boner",
  "A nipple hair named Steve",
  "The smell of napalm in the morning",
  "Tucking your twig and berries between your legs to make a man-noune",
  "Santa's balls draped over your nose",
  "A fierce tuck",
  "Scratchy toilet paper from the dollar store",
  "A confetti cannon full of fetuses",
  "A pimped out tractor with unicorns painted on it",
  "Jesus' shredded 6-pack",
  "That scab you can't help picking at all day",
  "A lawn gnome called Jebediah",
  "A dead semen-covered child pageant queen in a basement",
  "Whoopin' your kid just for being a kid",
  "That motherfucking snot that makes your nose whistle annoyingly",
  "Breast milk cheese",
  "A botched boob job",
  "Spreading the labia across your mouth and breathing like Darth Vader",
  "Smoking dope with grandma",
  "Grandma's dusty muffin",
  "A family-sized poutine from S&G's",
  "A dank cellar full of pickled human parts",
  "Crying into a bucket of KFC listening to Adele in a dark basement",
  "Eyes like Sloth from Goonies",
  "Informer by Snow",
  "That time you thought it was a fart but were severely mistaken",
  "You poor, unfortunate souls!",
  "Getting tugged by each and every one of Ursula's tentacles",
  "Dolores Umbridge",
  "Nailing Ursula but then realizing it was Barney dressed in drag",
  "Piece of shit spiders",
  "The diabetes",
  "Singing 'Surfin' Bird' while surfing on a bird",
  "Adorable spiders",
  "Cunt Soup",
  "Cunt Soap",
  "Realizing as you are balls deep in the mother of your children that you are, in fact, an actual motherfucker",
  "Anal Beads",
  "Big-assed ears",
  "Wasps?",
  "Like, 100 bloodsuckers on the end of your cork",
  "Being stuck in an elevator full of pomeranian puppies",
  "Spit-roasting a Golden Girl",
  "Hermetically sealed shame basket",
  "Sarlacc Pit",
  "A sad yank",
  "Wearing more cum than Monica Lewinsky's dress",
  "Rubbin' one out with chopsticks",
  "Justin Trudeau's hair",
  "A rub n tug",
  "Two Taint Marie",
  "Drawing lots of pictures of dicks",
  "A sweaty gooch",
  "A picture of a cock",
  "Swamp ass",
  "DILF",
  "Ponderosa",
  "A Laotian named Jujubee",
  "Karen from finance",
  "Priests with a penchant for peen",
  "An endearing crack whore",
  "A ladyboy from Thailand",
  "Trinni Trannies",
  "Sucking the warm yogurt out of a used condom",
  "A goblin on viagra",
  "Placenta juice",
  "Dame Edna's Playboy centerfold",
  "Spicy dick milk",
  "A flimsy foot job",
  "A bunch of Charlies sewing wallets",
  "Two pork chops nailed to a barn door",
  "Belly button lint",
  "Get handsy with a pug",
  "Stuck on an island with a lotta bitches",
  "A bitch slap",
  "Dirty whores",
  "The Star Wars Imperial March song",
  "Mr. Dressup in lingerie",
  "Actually being sick on a 'sick day'",
  "A high class Russian whore",
  "Never doing the follow-up jiggle",
  "Is that a rash or a herpes sore?",
  "Joking about mean shit",
  "Hans Moleman's flood pants",
  "A weiner dog with a big weiner",
  "A frosty mitten job in Nunavut",
  "Really really tight pants",
  "One of them throat cancer holes",
  "A metric fucktruck of lukewarm mucus",
  "Nipples that look in 2 different directions.",
  "A prepubescent boy choir singing Pull My Hair",
  "Some hot incest porn",
  "Getting side-eye from a hobo with a skullet",
  "An old Asian with a bum knee",
  "Curb-Stomped",
  "Getting curb stomped",
  "A rez chick only wearing one sock",
  "A frugal stripper named Marge",
  "Hardcore Mahjong",
  "A vasectomy using a butterknife",
  "Fingering the shitoris",
  "A toothy blowjob",
  "A saggy pair of man tits",
  "A tasteful melange of dick pics",
  "A gaggle of nuns doing the Thriller dance",
  "A struggle snuggle",
  "Nutting all over Henry Cavill's deliciously hairy pectorals",
  "Jamming a jar full of human parts for later consumption",
  "A blessing of unicorns",
  "ALLAHU AKBAR!",
  "A rapey uncle cult",
  "Deep-throating a banana for no particular reason",
  "Using shrinkage to your advantage",
  "Cock socks",
  "A beard made out of my back hair",
  "A naked midget riding a mini pony while wearing a nacho hat and setting the drapes on fire",
  "My sisters",
  "Finally grabbing a sweet handful of my dead aunt's boob at her open casket wake",
  "That tampon I shoved too deep inside of myself and forgot about for 3 months",
  "Putting a live gerbil in a condom and shoving it up my anus",
  "CHOO CHOO, MOTHERFUCKERS!",
  "Taking control of my life and finally becoming the molestor, no longer the molestee",
  "Fucking foosball",
  "Jerking off while getting birthday cake mushed into my face",
  "A really long pube... like, triple curled pube",
  "A ziploc bag full of yeast infection",
  "Gettin' crazy with the Cheez Whiz",
  "Hermione Granger, cuz she's 'of age' now",
  "Making girls say the word 'cunt' cuz they hate it",
  "Form the banana... form, form the banana...",
  "Pretending to be retarded when you're just numb from the dentist",
  "Getting jetpacked by Frodo Baggins",
  "Sloth from The Goonies",
  "Bilbo Baggins",
  "Ron Jeremy",
  "Lactation Porn",
  "Donald Trump's rectum",
  "Anne Frank",
  "Sexing a cat in heat using a baby carrot",
  "Foreskin",
  "The mythical clitoris",
  "Dolly Parton's areolas",
  "Finger lickin good",
  "Meow Mix",
  "Mix Cialis and Viagra and ride it out",
  "Uterine lining",
  "Hotter than Hades' anus",
  "Those monkeys with the red arses",
  "Secretly pullin' my pud in church",
  "So much corn",
  "Those little finger condoms",
  "Saying something is halal when it's totally no-lal",
  "The Charleston",
  "An empty dog scrotum",
  "Big polish sausage",
  "A stormtrooper making a storm pooper",
  "Miss Cleo's fortuney tits",
  "A soggy McGriddle",
  "A formidable cunt",
  "Fucking a bagel till you blow creamy dick milk all over it",
  "A ferociously fudge-packed brownie",
  "Inspector Gadget's helicopter tongue",
  "When people don't click the motherfucking reply all button",
  "Robots in disguise",
  "A whole bowl of toenails for breakfast",
  "Erotically licking a Tootsie Roll pop and getting a woody",
  "Mitochondrial DNA",
  "Making a Murderer",
  "A shit sandwich",
  "Rubbin' one in",
  "A brojob",
  "Brogurt",
  "A couple of hobos shitting in a bucket",
  "Parking the pork bus in tuna town",
  "Fried bologna and bannock",
  "A BuzzFeed list of 16 ways to take a satisfying shit",
  "Wiping back to front",
  "Homo-erotic dreams",
  "An old man's used handkerchief during flu season",
  "A cum rag",
  "Lying back trying not to move while he's getting the cum rag",
  "A paperclip Prince Albert",
  "Tits as big as basketballs",
  "A swimming pool full of severed labia",
  "The arse-end of a skunk",
  "The number of licks to get to the centre of a shit-filled Tootsie Roll pop",
  "Manscaping",
  "A manscaped noodle",
  "Herpes so bad your face belongs on the Walking Dead",
  "The fat kid from The Goonies doing the 'Truffle Shuffle'",
  "Gently cupping a cow's udder",
  "Psychopaths that put ketchup on their French toast",
  "Swiffering the floor with my taint",
  "Bed sheets covered in Russian hooker urine",
  "A sock full of pubic hair",
  "Cutting off your own foreskin at your Bris",
  "Smokin' a bowl of dryer lint",
  "9/11",
  "Moonwalking like Michael Jackson, but without the pedophilia",
  "Touching Macaulay Culkin at Neverland Ranch",
  "Watching Shaving Ryan's Privates and wondering why Tom Hanks isn't in it",
  "A firm, yet arousing, handshake",
  "Lesbianism",
  "Cutting a bitch",
  "Chyna's rotted troll vagina, may she rest in peace",
  "Masturbating to my grandma's sex tape",
  "A gross hipster moustache",
  "Motorboating chesticles",
  "A bull dyke named Vivian",
  "Suck it, Trebek!!",
  "An ass full of Legos",
  "Needs more cowbell",
  "Putting clothes pins on my nipples",
  "Binging and purging",
  "A yard bag of medicinal marijuana",
  "Dying seductively",
  "Going in dry",
  "Dungeons and Dragons",
  "A bitter divorce",
  "Rage fucking",
  "Riding dirty",
  "Being a straight-up motherfucking dick pig",
  "Ruptured hemorrhoids",
  "Vaping a bowl of pubic hair",
  "Sexy mermen",
  "A compound fracture",
  "The new Crayola crayon color: dog cock red",
  "Shit, piss... and more shit.",
  "Getting a Prince Alberted cock caught in your tonsils",
  "Fish Tacos",
  "AIDS",
  "A cute chick with a massive muff",
  "Every fucking thing I own",
  "Anxiously awaiting your turn while your uncle works his way through your older siblings",
  "A piece of shit cock-suckin labia-lickin motherfuckin cuntbucket ass face scabby cervix chewing crusty dickhead cat",
  "A vibrator that plays Celine Dion's 'All By Myself' when turned on",
  "Those weird moans deaf people make when they try to talk",
  "A stripper with no drapes, all carpet",
  "A spreadsheet of scheduled, organized fun.",
  "Knee-deep in the dead",
  "GET TO THE CHOPPA!!!!!",
  "A blue-titted booby",
  "Stuck in Arkham Asylum with Harley Quinn",
  "Erotically sucking a big nose",
  "A clown that honks your penis instead of his nose",
  "A bag of parsley you thought was weed",
  "An overweight asthmatic chain-smoking 911 dispatcher",
  "Your average run-of-the-mill Russian bisexual transvestite hooker",
  "Meat",
  "Mjolnir'in some Asgard",
  "The new Google Pixelbook!!!",
  "A spider monkey with a raging hard-on",
  "Nits",
  "An alarmingly full diva cup",
  "Vajoina",
  "Yoda's gherkin",
  "Girl goo",
  "Deez nuts",
  "A silky merkin",
  "Not working Wednesdays",
  "Anya on Coke",
  "Giordy's Balls",
  "Sarah's tight grasp on Jon's balls",
  "Rich seeing color for the first time",
  "Ali with a chainsaw",
  "Babies with tablets",
  "A Pigale's urinal puck",
  "Microwaved hot dogs",
  "Incest",
  "Autism",
  "Drugging the office coffee",
  "Escaped Ferrets",
  "Aaron Neville's pulsating mole",
  "Eating corn chips and masturbating",
  "Humping doorknobs",
  "Eating a tray of Toffifee for dinner",
  "Toddler dentures",
  "Bloody papercuts",
  "Sharon's Instagram pics",
  "Kurt Cobain's shotgun",
  "The emergency room floor",
  "Exact replicas of the Easter Island heads",
  "Paper mache vulvas",
  "The cast of Full House",
  "The slut from Degrassi Junior High",
  "Shooting seagulls with a potato gun",
  "Kylie Jenner's real lips",
  "Dusan rolling out of a ditch",
  "Kim's ego",
  "Frodo's tight little squirrel bum",
  "Cyndi's awesome email poems",
  "Tonsil rocks",
  "Machine gun diarrhea",
  "Eric Houle's only black tie",
  "Warren's cowboy boots",
  "Mullet man's mangey dog",
  "Horny Dwyer",

  // ============================================================
  // GENERATED WHITE CARDS
  // ============================================================
  "A Roomba that only finds your vibrator",
  "Snoop Dogg's personal blunt roller",
  "A prostate exam from Edward Scissorhands",
  "Weaponized dildos",
  "Aggressively sensual eye contact with a llama",
  "Chris Hemsworth's sweaty jockstrap",
  "The entire cast of Sesame Street in a hot tub",
  "Shrek's earwax candle collection",
  "A fanny pack full of loose teeth",
  "Danny DeVito crawling out of a leather couch naked",
  "Competitive colonoscopies",
  "A sensual PowerPoint presentation",
  "Farting during a prostate exam",
  "Nicolas Cage's search history",
  "Accidentally sexting your boss",
  "The sound of two balloons rubbing together",
  "Fermented placenta smoothie",
  "Drunk-dialing Jesus",
  "A condom full of bees",
  "Getting pegged by a Care Bear",
  "Gandalf's long, wise, pulsating staff",
  "Accidentally calling your teacher 'Mommy' at age 35",
  "A bathtub full of expired mayonnaise",
  "Post-Taco Bell regret",
  "SpongeBob's porous and absorbent body",
  "The Rock smoldering at you while eating pancakes",
  "Elon Musk's body odor",
  "An uncomfortably long handshake with a politician",
  "Aggressive nipple tweaking",
  "That one uncle who always smells like salami",
  "Queefing during yoga class",
  "The entire Bee Movie script tattooed on my back",
  "A haunted Fleshlight",
  "Snorting Fun Dip off a stripper's thigh",
  "Darth Vader's breathing during intercourse",
  "Skinny-dipping in a Denny's dumpster",
  "An erotic puppet show",
  "Guy Fieri taking you to Flavor Town",
  "Butt-chugging maple syrup",
  "A life-sized Nicolas Cage body pillow",
  "Weaponized glitter",
  "Getting catfished by your own mother",
  "Licking the floor of a Greyhound bus",
  "The wet slapping sound of raw chicken",
  "A glory hole at a dental office",
  "Reverse cowgirling a mechanical bull",
  "Deep-frying your own hand",
  "An orgy at the retirement home",
  "Finding your dad's OnlyFans",
  "Passionately making out with a CPR dummy",
  "A rectal thermometer with bite marks",
  "Accidentally joining a cult because the snacks were good",
  "Shaquille O'Neal's shower flip-flops",
  "A USB drive full of unspeakable things",
  "Microwaving fish in the office kitchen",
  "The sound a wet flip-flop makes on bare feet",
  "Crying during sex and pretending it's sweat",
  "A dominatrix who is also your accountant",
  "Full-body waxing with duct tape",
  "Two raccoons in a trench coat on a date",
  "A really aggressive game of Twister",
  "Getting a lap dance from Gollum",
  "The back of a Waffle House at 3 AM",
  "A seductive yet menacing clown",
  "Oprah giving away bees",
  "Sweating profusely in a job interview",
  "Rubbing one out to the Home Depot theme song",
  "Sending unsolicited pics of your feet to the Pope",
  "A sex dungeon with a really nice throw rug",
  "An interpretive dance about diarrhea",
  "A strongly worded letter to my hemorrhoids",
  "Drinking pickle juice out of a shoe",
  "A Craigslist ad for a used catheter",
  "Accidentally making eye contact through the bathroom stall gap",
  "A motivational speech by a meth-addled raccoon",
  "Tom Hanks aggressively whispering sweet nothings",
  "Bob Ross painting happy little nipples",
  "The janitor's bucket of mysterious fluid",
  "An emotional support stripper",
  "Waking up handcuffed to a radiator in Tijuana",
  "Furries at a funeral",
  "Dolly Parton's tax returns",
  "A Yelp review for a colonoscopy clinic",
  "Sensually peeling a banana while maintaining eye contact",
  "Getting pantsed at your own wedding",
  "A surprise finger during a massage",
  "Twerking at a funeral",
  "A very enthusiastic gynecologist",
  "The inside of a sumo wrestler's thong",
  "Cardi B reading bedtime stories",
  "A Brazilian wax gone horribly wrong",
  "An escape room but it's just a Port-A-Potty",
  "Morgan Freeman narrating your bowel movements",
  "A snake in your toilet just vibing",
  "Grandpa's secret sock drawer",
  "The wrong hole",
  "Eating cereal out of a frisbee because all the bowls are dirty",
  "A heated argument between two Karens",
  "The chunky bits in expired milk",
  "Getting friendzoned by a prostitute",
  "Shakespeare if he were really, really drunk",
  "The crusty sock under your teenage son's bed",
  "A feral child raised by Roombas",
  "Tantric yoga with Danny DeVito",
  "Involuntarily clenching during a sneeze",
  "Lemon juice on a paper cut",
  "The squishy sound of wet socks",
  "One singular, magnificent ass hair",
  "A motivational poster featuring a prolapsed rectum",
  "That weird sticky spot on the movie theater floor",
  "A gender reveal party that summons a demon",
  "Hobbit feet pics",
  "Mario's plumber's crack",
  "Being the little spoon but you're both 6'4\"",
  "Texting 'I love you' to your Uber driver",
  "A colonoscopy livestream on Twitch",
  "Gordon Ramsay's disappointed face during sex",
  "The Wiggles doing a world tour with Slayer",
  "Accidentally liking your ex's photo from 2014",
  "A haunted bidet",
  "Three words: moist panini press",
  "Getting Rick-Rolled at your own funeral",
  "A support group for people who cry at IKEA",
  "Jeff Goldblum doing literally anything",
  "A lap dance from a Furby",
  "Flossing with a stranger's hair",
  "The sound your stomach makes during a silent exam",
  "Keanu Reeves gently holding your face and calling you breathtaking",
  "Benedict Cumberbatch's cheekbones used as a cheese grater",
  "An aggressively enthusiastic proctologist",
  "Soggy Crocs",
  "The entire Shrek franchise on a single VHS tape",
  "Competitive yodeling in a Wendy's parking lot",
];
