// Nerds Against Humanity — Full Card Deck
// Original cards from the spreadsheet + generated cards to fill out the deck

import {
  themes,
  scifiBlackCards, scifiWhiteCards,
  fantasyBlackCards, fantasyWhiteCards,
  nostalgiaBlackCards, nostalgiaWhiteCards,
  horrorBlackCards, horrorWhiteCards,
  scienceBlackCards, scienceWhiteCards,
} from './themes.js';

export { themes };

const standardBlackCards = [
  // ============================================================
  // ORIGINAL BLACK CARDS (from the spreadsheet)
  // ============================================================
  { text: "New at McDonald's - The Morning Mc_____ !", pick: 1 },
  { text: "The secret ingredient in McDonald's hash browns is _____.", pick: 1 },
  { text: "What Spuds MacKenzie is doing RIGHT now.", pick: 1 },
  { text: "Sorry I'm late for work. I was just _____.", pick: 1 },
  { text: "What's that buzzing sound?", pick: 1 },
  { text: "Tinky Winky carries _____ in his man-purse.", pick: 1 },
  { text: "\"Everybody get up, it's time to slam now. We got a real jam going down. Welcome to the _____\"", pick: 1 },
  { text: "\"Weird, I just got an email from a Nigerian prince saying he'll give me _____ if I send him _____\"", pick: 2 },
  { text: "\"It's rainin' men... Hallelujah, it's rainin' _____\"", pick: 1 },
  { text: "Little known Star Wars fact: Yoda would often use the Force to _____ when he was bored.", pick: 1 },
  { text: "_____. That's what they used to call me back in kindergarten.", pick: 1 },
  { text: "\"If you can't love yourself, how in the hell are you supposed to love _____? Can I get an amen?!\"", pick: 1 },
  { text: "What they should shoot out of confetti cannons at child beauty pageants.", pick: 1 },
  { text: "The worst line of Happy Meal toys.", pick: 1 },
  { text: "Rudolph the Red-Nosed _____", pick: 1 },
  { text: "\"In the gay community, there are Bears, Otters, Twinks and _____\"", pick: 1 },
  { text: "\"Our Father, who art in Heaven. Hallowed be thy _____\"", pick: 1 },
  { text: "\"Don't cry over spilled milk... Instead, cry over _____\"", pick: 1 },
  { text: "\"This Summer, Gandalf returns as he and the Hobbits do battle with _____\"", pick: 1 },
  { text: "Toy Story 4: Buzz and Woody are _____", pick: 1 },
  { text: "What Mike Dwyer keeps hidden from the world.", pick: 1 },
  { text: "\"Mom, I accidentally caught you and dad _____\"", pick: 1 },
  { text: "\"Girls simply don't like the word 'cunt'. Instead we shall name it _____.\"", pick: 1 },
  { text: "New to Big Rig's menu: _____", pick: 1 },
  { text: "\"Forget the cardboard... These days, breakdancers cut it loose on _____.\"", pick: 1 },
  { text: "Hey Otis... Hold my beer while I _____", pick: 1 },
  { text: "How would I describe Sheila? Hmmm... She's definitely _____", pick: 1 },
  { text: "Why doesn't my mom love me anymore?", pick: 1 },
  { text: "This is my favorite thing to put in my mouth.", pick: 1 },
  { text: "These tears in my eyes aren't from crying... They're from _____", pick: 1 },
  { text: "\"Tonight, in the WWE, Hulk Hogan is set to take on _____ in the Hell in a Cell cage match!!\"", pick: 1 },
  { text: "\"If every time a bell rings, an angel gets its wings, then every time _____, Yan gets _____\"", pick: 2 },
  { text: "\"In prison, Jared Fogel passes time by drawing pictures of _____\"", pick: 1 },
  { text: "\"Don't go too far, chum. I wanna _____\"", pick: 1 },
  { text: "The dowry for my daughter is _____", pick: 1 },
  { text: "_____, that's what society needs right now!", pick: 1 },
  { text: "\"(Sing This:) If you like Pina Coladas, and _____\"", pick: 1 },
  { text: "\"Oh baby, I'm going to rock your world tonight. Get ready for some filthy talking and some _____\"", pick: 1 },
  { text: "Sometimes I'll _____ when I can't sleep at night.", pick: 1 },
  { text: "(Sing This:) Hello darkness my old friend... I've come to _____", pick: 1 },
  { text: "Why does Buckley's taste so bad?", pick: 1 },
  { text: "Before becoming a rock legend Slash would pass the time _____ to make ends meet.", pick: 1 },
  { text: "Why is my face wet?", pick: 1 },
  { text: "Tune in to Making a Murderer: Season 3 where Steven Avery is _____", pick: 1 },
  { text: "\"To turn their season around, the Ottawa Senators tried _____ to boost morale.\"", pick: 1 },
  { text: "The key ingredient to maintaining Donald Trump's hair-do: _____", pick: 1 },
  { text: "I would give _____ for one no-questions-asked night with Henry Cavill.", pick: 1 },
  { text: "\"In an attempt to discover a new thrilling high, Charlie Sheen tried snorting _____.\"", pick: 1 },
  { text: "And the Teen Choice Award for _____ goes to... _____", pick: 2 },
  { text: "\"Download Adele's new single _____, a song about _____. Available on iTunes\"", pick: 2 },
  { text: "\"I didn't have any change on me, so I put _____ in the kids' Unicef boxes\"", pick: 1 },
  { text: "\"Santa gives good kids _____, shitty kids get _____.\"", pick: 2 },
  { text: "(Sing This:) All I want for Christmas is _____.", pick: 1 },
  { text: "_____. Yep, it DOES taste like chicken!!", pick: 1 },
  { text: "\"(Sing This:) When the moon hits your eye like a _____, that's AMORE!!\"", pick: 1 },
  { text: "\"Ottawa Police tech company 'Versaterm' has reduced crime in the Ottawa area with a new technique involving _____\"", pick: 1 },
  { text: "Breaking news, Coronavirus has been cured from _____.", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "And the Academy Award for _____ goes to _____.", pick: 2 },
  { text: "New research has proven that people with _____ are more likely to lead a happier life.", pick: 1 },
  { text: "\"That's right, I killed _____. How you ask? _____\"", pick: 2 },
  { text: "The new Versaterm logo goes back to our roots and will incorporate _____", pick: 1 },
  { text: "I like to hit _____ with _____", pick: 2 },
  { text: "You make me feel like a natural _____", pick: 1 },
  { text: "My perfect date night would start with _____ and end with _____", pick: 2 },
  { text: "I like big _____ and I cannot lie", pick: 1 },
  { text: "Life is like a box of _____", pick: 1 },
  { text: "I'd replace the Versaterm bathroom jokes with _____", pick: 1 },
  { text: "\"Next time we go for sushi, we are not ordering _____\"", pick: 1 },
  { text: "\"The casino night is gonna be lit, I'm gonna _____ in _____\"", pick: 2 },
  { text: "Ivan had _____ delivered to Versaterm", pick: 1 },
  { text: "I saw Laporte put _____ into the coffee maker", pick: 1 },
  { text: "I really admire _____", pick: 1 },
  { text: "\"Sometimes, when I'm lonely, I find myself fantasizing about _____\"", pick: 1 },
  { text: "Many _____ make light work", pick: 1 },
  { text: "You'll catch more _____ with _____ than with vinegar", pick: 2 },
  { text: "Like herding _____", pick: 1 },
  { text: "One man's trash is another man's _____", pick: 1 },
  { text: "There's more than one way to skin a _____", pick: 1 },

  // ============================================================
  // GENERATED BLACK CARDS
  // ============================================================
  { text: "TSA pulled me aside and found _____ crammed in my prison wallet.", pick: 1 },
  { text: "\"Babe, I swear it's not what it looks like. I was just _____ and things got out of hand.\"", pick: 1 },
  { text: "Pornhub's fastest growing category of 2026: _____.", pick: 1 },
  { text: "\"I'm not saying I'd suck a dick for _____, but I'm not NOT saying it either.\"", pick: 1 },
  { text: "Florida Man arrested for _____ in a Wendy's parking lot at 3 AM.", pick: 1 },
  { text: "\"One time, at band camp, I shoved _____ up my _____\"", pick: 2 },
  { text: "What the fuck is Hagrid breeding in the Forbidden Forest?", pick: 1 },
  { text: "\"Dear Diary, today I discovered that if you combine _____ with _____, you get arrested.\"", pick: 2 },
  { text: "\"The autopsy revealed that cause of death was, in fact, _____.\"", pick: 1 },
  { text: "What's actually in the ball pit at Chuck E. Cheese?", pick: 1 },
  { text: "\"I wasn't THAT drunk last night.\" \"Dude, you were _____.\"", pick: 1 },
  { text: "Leaked internal memo from Disney: \"Under no circumstances should any employee mention _____ near the children.\"", pick: 1 },
  { text: "The next Grindr feature: swipe right for _____.", pick: 1 },
  { text: "What's Shrek doing in his swamp when nobody's watching?", pick: 1 },
  { text: "\"My uncle taught me two things growing up: hard work and _____.\"", pick: 1 },
  { text: "\"It's not gay if it's _____\"", pick: 1 },
  { text: "Satan's guilty pleasure: _____.", pick: 1 },
  { text: "What's the real reason your dad went out for smokes and never came back?", pick: 1 },
  { text: "\"And the Lord said unto Moses: 'Thou shalt not _____ thy neighbor's _____.\"", pick: 2 },
  { text: "\"Doctor, every time I _____, my _____ starts throbbing.\"", pick: 2 },
  { text: "The Catholic Church would like to formally apologize for _____.", pick: 1 },
  { text: "What did the Make-A-Wish kid actually wish for?", pick: 1 },
  { text: "\"I'd rather staple my dick to a ceiling fan than _____\"", pick: 1 },
  { text: "\"Tonight on Dateline: 'He seemed so normal, until police found _____ in his crawl space.'\"", pick: 1 },
  { text: "Little-known fact: Willy Wonka's factory was shut down by the health inspector for _____.", pick: 1 },
  { text: "The real walk of shame isn't leaving someone's apartment — it's _____.", pick: 1 },
  { text: "What's hiding in Gandalf's long-ass beard?", pick: 1 },
  { text: "\"Stop kink-shaming me. _____ is a perfectly valid lifestyle.\"", pick: 1 },
  { text: "The most disappointing thing about losing your virginity: _____.", pick: 1 },
  { text: "Next season on Naked and Afraid: surviving 21 days with nothing but _____ and _____.", pick: 2 },
  { text: "\"My grandma's dying words were '_____'\"", pick: 1 },
  { text: "What would make a funeral genuinely entertaining?", pick: 1 },
  { text: "\"I'm not racist, BUT _____\"", pick: 1 },
  { text: "The thing your search history says about you that you'll deny to your grave: _____.", pick: 1 },
  { text: "\"Step 1: _____. Step 2: _____. Step 3: Profit.\"", pick: 2 },
  { text: "What does R2-D2 keep in that compartment he never opens?", pick: 1 },
  { text: "The next Cards Against Humanity expansion pack: _____ Edition.", pick: 1 },
  { text: "(Sing This:) Doin' it and doin' it and doin' it well. I represent _____, now who the hell...", pick: 1 },
  { text: "\"What's the WiFi password?\" \"It's _____\"", pick: 1 },
  { text: "\"Congrats to the newlyweds! May your marriage be full of _____ and _____!\"", pick: 2 },
  { text: "The reason nobody invites Gary to parties anymore: _____.", pick: 1 },
  { text: "\"Yer a wizard, Harry!\" \"And yer a _____, Hagrid.\"", pick: 1 },
  { text: "The morning-after pill, but for _____.", pick: 1 },
  { text: "\"I tried _____ once. I woke up three days later in Tijuana with no pants and _____.\"", pick: 2 },
  { text: "What the school guidance counselor should have warned us about: _____.", pick: 1 },
  { text: "\"WORLDSTAR!! Did you SEE that dude _____ in front of EVERYONE?!\"", pick: 1 },
  { text: "What does the fox ACTUALLY say?", pick: 1 },
  { text: "Canada's dirtiest little secret: _____.", pick: 1 },
  { text: "If there's a sock on the doorknob, it means your roommate is _____.", pick: 1 },
  { text: "\"I clogged the toilet with _____. Again.\"", pick: 1 },
  { text: "What got Jesus REALLY nailed to that cross?", pick: 1 },
  { text: "\"Your Honor, my client pleads not guilty by reason of _____.\"", pick: 1 },
  { text: "\"How do I explain _____ to my children?\"", pick: 1 },
  { text: "What do flat-earthers and _____ have in common?", pick: 1 },
  { text: "\"I walked in on Grandpa _____ and I can never unsee it.\"", pick: 1 },
  { text: "\"The coroner pulled back the sheet and said, 'Yep. That's definitely _____.\"", pick: 1 },
  { text: "Coming this fall to TLC: My Strange Addiction to _____.", pick: 1 },
  { text: "\"Dear Santa, this year I've been naughty. Please bring me _____.\"", pick: 1 },
  { text: "What the janitor at Hogwarts has to clean up every goddamn night: _____.", pick: 1 },
  { text: "\"I'm not addicted to _____. I can stop whenever I want. I just don't want to.\"", pick: 1 },
  { text: "What makes prison inmates cry at night?", pick: 1 },
  { text: "\"When I lost my virginity, she said I reminded her of _____. I haven't recovered since.\"", pick: 1 },
  { text: "\"You call it _____, I call it a Tuesday night.\"", pick: 1 },
  { text: "\"What are you doing, step-bro?\" \"Just _____.\"", pick: 1 },
  { text: "\"911, what's your emergency?\" \"Sir, there's _____ and it won't stop _____\"", pick: 2 },
  { text: "\"Name something you'd find in a frat house dumpster.\" \"_____\"", pick: 1 },
  { text: "The worst thing to do with peanut butter when nobody's home: _____.", pick: 1 },
  { text: "\"My safe word is _____, but nobody ever listens.\"", pick: 1 },
  { text: "\"I blacked out at the company Christmas party and apparently I _____\"", pick: 1 },
];

const standardWhiteCards = [
  // ============================================================
  // ORIGINAL WHITE CARDS (from the spreadsheet)
  // ============================================================
  "Thinking Barney the Dinosaur is pretty much Grimace, but gayer.",
  "Ronald McDonald's curly red pubes.",
  "A van full of drag queens on their way to a wig sale",
  "Zombie Chihuahuas!!",
  "A human carcass flailing dangerously from a ceiling fan on high speed",
  "A house centipede nesting in your urethra",
  "An old Russian that doesn't wash his hands after peeing",
  "Licking Bill Cosby's pudding pop.",
  "A Cosby Sweater",
  "Donkey Punching a priest",
  "Playing the rusty trombone",
  "Gargling mayonnaise",
  "Cradle the balls, stroke the shaft and swallow the gravy",
  "Vaginal discharge",
  "Using a gloworm as anal beads",
  "He-Man!! AND THE MASTERS OF THE UNIVERSE!!!",
  "Watch me whip... now watch me nay-nay",
  "A dog's firetruck red boner",
  "A nipple hair named Steve",
  "The smell of napalm in the morning",
  "Tucking your twig and berries between your legs to make a man-noune",
  "Santa's balls draped over your nose",
  "A fierce tuck",
  "Scratchy toilet paper from the dollar store",
  "A confetti cannon full of fetuses",
  "A pimped out tractor with unicorns painted on it",
  "Jesus' shredded 6-pack",
  "That scab you can't help picking at all day",
  "A lawn gnome called Jebediah",
  "A dead semen-covered child pageant queen in a basement",
  "Whoopin' your kid just for being a kid",
  "That motherfucking snot that makes your nose whistle annoyingly",
  "Breast milk cheese",
  "A botched boob job",
  "Spreading the labia across your mouth and breathing like Darth Vader",
  "Smoking dope with grandma",
  "Grandma's dusty muffin",
  "A family-sized poutine from S&G's",
  "A dank cellar full of pickled human parts",
  "Crying into a bucket of KFC listening to Adele in a dark basement",
  "Eyes like Sloth from Goonies",
  "Informer by Snow",
  "That time you thought it was a fart but were severely mistaken",
  "You poor, unfortunate souls!",
  "Getting tugged by each and every one of Ursula's tentacles",
  "Dolores Umbridge",
  "Nailing Ursula but then realizing it was Barney dressed in drag",
  "Piece of shit spiders",
  "The diabetes",
  "Singing 'Surfin' Bird' while surfing on a bird",
  "Adorable spiders",
  "Cunt Soup",
  "Cunt Soap",
  "Realizing as you are balls deep in the mother of your children that you are, in fact, an actual motherfucker",
  "Anal Beads",
  "Big-assed ears",
  "Wasps?",
  "Like, 100 bloodsuckers on the end of your cork",
  "Being stuck in an elevator full of pomeranian puppies",
  "Spit-roasting a Golden Girl",
  "Hermetically sealed shame basket",
  "Sarlacc Pit",
  "A sad yank",
  "Wearing more cum than Monica Lewinsky's dress",
  "Rubbin' one out with chopsticks",
  "Justin Trudeau's hair",
  "A rub n tug",
  "Two Taint Marie",
  "Drawing lots of pictures of dicks",
  "A sweaty gooch",
  "A picture of a cock",
  "Swamp ass",
  "DILF",
  "Ponderosa",
  "A Laotian named Jujubee",
  "Karen from finance",
  "Priests with a penchant for peen",
  "An endearing crack whore",
  "A ladyboy from Thailand",
  "Trinni Trannies",
  "Sucking the warm yogurt out of a used condom",
  "A goblin on viagra",
  "Placenta juice",
  "Dame Edna's Playboy centerfold",
  "Spicy dick milk",
  "A flimsy foot job",
  "A bunch of Charlies sewing wallets",
  "Two pork chops nailed to a barn door",
  "Belly button lint",
  "Get handsy with a pug",
  "Stuck on an island with a lotta bitches",
  "A bitch slap",
  "Dirty whores",
  "The Star Wars Imperial March song",
  "Mr. Dressup in lingerie",
  "Actually being sick on a 'sick day'",
  "A high class Russian whore",
  "Never doing the follow-up jiggle",
  "Is that a rash or a herpes sore?",
  "Joking about mean shit",
  "Hans Moleman's flood pants",
  "A weiner dog with a big weiner",
  "A frosty mitten job in Nunavut",
  "Really really tight pants",
  "One of them throat cancer holes",
  "A metric fucktruck of lukewarm mucus",
  "Nipples that look in 2 different directions.",
  "A prepubescent boy choir singing Pull My Hair",
  "Some hot incest porn",
  "Getting side-eye from a hobo with a skullet",
  "An old Asian with a bum knee",
  "Curb-Stomped",
  "Getting curb stomped",
  "A rez chick only wearing one sock",
  "A frugal stripper named Marge",
  "Hardcore Mahjong",
  "A vasectomy using a butterknife",
  "Fingering the shitoris",
  "A toothy blowjob",
  "A saggy pair of man tits",
  "A tasteful melange of dick pics",
  "A gaggle of nuns doing the Thriller dance",
  "A struggle snuggle",
  "Nutting all over Henry Cavill's deliciously hairy pectorals",
  "Jamming a jar full of human parts for later consumption",
  "A blessing of unicorns",
  "ALLAHU AKBAR!",
  "A rapey uncle cult",
  "Deep-throating a banana for no particular reason",
  "Using shrinkage to your advantage",
  "Cock socks",
  "A beard made out of my back hair",
  "A naked midget riding a mini pony while wearing a nacho hat and setting the drapes on fire",
  "My sisters",
  "Finally grabbing a sweet handful of my dead aunt's boob at her open casket wake",
  "That tampon I shoved too deep inside of myself and forgot about for 3 months",
  "Putting a live gerbil in a condom and shoving it up my anus",
  "CHOO CHOO, MOTHERFUCKERS!",
  "Taking control of my life and finally becoming the molestor, no longer the molestee",
  "Fucking foosball",
  "Jerking off while getting birthday cake mushed into my face",
  "A really long pube... like, triple curled pube",
  "A ziploc bag full of yeast infection",
  "Gettin' crazy with the Cheez Whiz",
  "Hermione Granger, cuz she's 'of age' now",
  "Making girls say the word 'cunt' cuz they hate it",
  "Form the banana... form, form the banana...",
  "Pretending to be retarded when you're just numb from the dentist",
  "Getting jetpacked by Frodo Baggins",
  "Sloth from The Goonies",
  "Bilbo Baggins",
  "Ron Jeremy",
  "Lactation Porn",
  "Donald Trump's rectum",
  "Anne Frank",
  "Sexing a cat in heat using a baby carrot",
  "Foreskin",
  "The mythical clitoris",
  "Dolly Parton's areolas",
  "Finger lickin good",
  "Meow Mix",
  "Mix Cialis and Viagra and ride it out",
  "Uterine lining",
  "Hotter than Hades' anus",
  "Those monkeys with the red arses",
  "Secretly pullin' my pud in church",
  "So much corn",
  "Those little finger condoms",
  "Saying something is halal when it's totally no-lal",
  "The Charleston",
  "An empty dog scrotum",
  "Big polish sausage",
  "A stormtrooper making a storm pooper",
  "Miss Cleo's fortuney tits",
  "A soggy McGriddle",
  "A formidable cunt",
  "Fucking a bagel till you blow creamy dick milk all over it",
  "A ferociously fudge-packed brownie",
  "Inspector Gadget's helicopter tongue",
  "When people don't click the motherfucking reply all button",
  "Robots in disguise",
  "A whole bowl of toenails for breakfast",
  "Erotically licking a Tootsie Roll pop and getting a woody",
  "Mitochondrial DNA",
  "Making a Murderer",
  "A shit sandwich",
  "Rubbin' one in",
  "A brojob",
  "Brogurt",
  "A couple of hobos shitting in a bucket",
  "Parking the pork bus in tuna town",
  "Fried bologna and bannock",
  "A BuzzFeed list of 16 ways to take a satisfying shit",
  "Wiping back to front",
  "Homo-erotic dreams",
  "An old man's used handkerchief during flu season",
  "A cum rag",
  "Lying back trying not to move while he's getting the cum rag",
  "A paperclip Prince Albert",
  "Tits as big as basketballs",
  "A swimming pool full of severed labia",
  "The arse-end of a skunk",
  "The number of licks to get to the centre of a shit-filled Tootsie Roll pop",
  "Manscaping",
  "A manscaped noodle",
  "Herpes so bad your face belongs on the Walking Dead",
  "The fat kid from The Goonies doing the 'Truffle Shuffle'",
  "Gently cupping a cow's udder",
  "Psychopaths that put ketchup on their French toast",
  "Swiffering the floor with my taint",
  "Bed sheets covered in Russian hooker urine",
  "A sock full of pubic hair",
  "Cutting off your own foreskin at your Bris",
  "Smokin' a bowl of dryer lint",
  "9/11",
  "Moonwalking like Michael Jackson, but without the pedophilia",
  "Touching Macaulay Culkin at Neverland Ranch",
  "Watching Shaving Ryan's Privates and wondering why Tom Hanks isn't in it",
  "A firm, yet arousing, handshake",
  "Lesbianism",
  "Cutting a bitch",
  "Chyna's rotted troll vagina, may she rest in peace",
  "Masturbating to my grandma's sex tape",
  "A gross hipster moustache",
  "Motorboating chesticles",
  "A bull dyke named Vivian",
  "Suck it, Trebek!!",
  "An ass full of Legos",
  "Needs more cowbell",
  "Putting clothes pins on my nipples",
  "Binging and purging",
  "A yard bag of medicinal marijuana",
  "Dying seductively",
  "Going in dry",
  "Dungeons and Dragons",
  "A bitter divorce",
  "Rage fucking",
  "Riding dirty",
  "Being a straight-up motherfucking dick pig",
  "Ruptured hemorrhoids",
  "Vaping a bowl of pubic hair",
  "Sexy mermen",
  "A compound fracture",
  "The new Crayola crayon color: dog cock red",
  "Shit, piss... and more shit.",
  "Getting a Prince Alberted cock caught in your tonsils",
  "Fish Tacos",
  "AIDS",
  "A cute chick with a massive muff",
  "Every fucking thing I own",
  "Anxiously awaiting your turn while your uncle works his way through your older siblings",
  "A piece of shit cock-suckin labia-lickin motherfuckin cuntbucket ass face scabby cervix chewing crusty dickhead cat",
  "A vibrator that plays Celine Dion's 'All By Myself' when turned on",
  "Those weird moans deaf people make when they try to talk",
  "A stripper with no drapes, all carpet",
  "A spreadsheet of scheduled, organized fun.",
  "Knee-deep in the dead",
  "GET TO THE CHOPPA!!!!!",
  "A blue-titted booby",
  "Stuck in Arkham Asylum with Harley Quinn",
  "Erotically sucking a big nose",
  "A clown that honks your penis instead of his nose",
  "A bag of parsley you thought was weed",
  "An overweight asthmatic chain-smoking 911 dispatcher",
  "Your average run-of-the-mill Russian bisexual transvestite hooker",
  "Meat",
  "Mjolnir'in some Asgard",
  "The new Google Pixelbook!!!",
  "A spider monkey with a raging hard-on",
  "Nits",
  "An alarmingly full diva cup",
  "Vajoina",
  "Yoda's gherkin",
  "Girl goo",
  "Deez nuts",
  "A silky merkin",
  "Not working Wednesdays",
  "Anya on Coke",
  "Giordy's Balls",
  "Sarah's tight grasp on Jon's balls",
  "Rich seeing color for the first time",
  "Ali with a chainsaw",
  "Babies with tablets",
  "A Pigale's urinal puck",
  "Microwaved hot dogs",
  "Incest",
  "Autism",
  "Drugging the office coffee",
  "Escaped Ferrets",
  "Aaron Neville's pulsating mole",
  "Eating corn chips and masturbating",
  "Humping doorknobs",
  "Eating a tray of Toffifee for dinner",
  "Toddler dentures",
  "Bloody papercuts",
  "Sharon's Instagram pics",
  "Kurt Cobain's shotgun",
  "The emergency room floor",
  "Exact replicas of the Easter Island heads",
  "Paper mache vulvas",
  "The cast of Full House",
  "The slut from Degrassi Junior High",
  "Shooting seagulls with a potato gun",
  "Kylie Jenner's real lips",
  "Dusan rolling out of a ditch",
  "Kim's ego",
  "Frodo's tight little squirrel bum",
  "Cyndi's awesome email poems",
  "Tonsil rocks",
  "Machine gun diarrhea",
  "Eric Houle's only black tie",
  "Warren's cowboy boots",
  "Mullet man's mangey dog",
  "Horny Dwyer",

  // ============================================================
  // GENERATED WHITE CARDS
  // ============================================================
  "Aggressively finger-blasting a bowl of mac and cheese",
  "A prostate exam from Captain Hook",
  "Rubbing one out in the McDonald's PlayPlace ball pit",
  "Voldemort's crusty nose hole used as a cock ring",
  "A queef so powerful it blows out birthday candles",
  "Hulk Hogan gently wiping your tears with his handlebar mustache",
  "Danny DeVito balls-deep in a Thanksgiving turkey",
  "Snorting a line of Parmesan off a hooker's tramp stamp",
  "A Roomba covered in cat shit carving a path through the living room",
  "Getting railed by Optimus Prime while he keeps transforming",
  "Shrek's used loofah",
  "Dry-humping the pile of coats at a house party",
  "Using a waffle iron on your taint",
  "A Fleshlight shaped like Jar Jar Binks' mouth",
  "The exact moment you realize it's not a queef",
  "Accidentally nutting during a job interview handshake",
  "Chewbacca's matted, cum-crusted back hair",
  "Gandalf screaming 'YOU SHALL NOT PASS' during a kidney stone",
  "Getting catfished by your own stepmom",
  "A cum-stained copy of the Bible",
  "Eating ass at an Arby's",
  "Gollum sensually whispering 'my precious' about your penis",
  "A golden shower in a Walmart bathroom",
  "Mr. Rogers aggressively twerking in his cardigan",
  "Using a power washer as a bidet",
  "A dick pic accidentally sent to the family group chat",
  "Farting into a Ziplock bag and huffing it later",
  "Giving a hand job with oven mitts on",
  "Two midgets jousting on Great Danes",
  "Thanos snapping away half your pubic hair",
  "A lactating She-Hulk",
  "Captain America's star-spangled cock sock",
  "Waking up with a traffic cone up your ass and no memory of the night before",
  "3 AM diarrhea that sounds like a standing ovation",
  "Gargling a stranger's bath water",
  "A prolapsed anus at show-and-tell",
  "SpongeBob absorbing all the bodily fluids in a motel room",
  "The wet spot on grandma's recliner",
  "Shaving your balls with a cheese grater",
  "Sliding into the DMs of your parole officer",
  "Getting a boner at your own grandmother's funeral",
  "Accidentally calling Siri during sex and she starts giving directions",
  "A nip slip during a baptism",
  "An erection that just won't quit during a prostate exam",
  "The Hamburglar stealing your virginity",
  "Spider-Man's sticky web and where it ACTUALLY comes from",
  "Dobby's shriveled little cock sock",
  "Shitting your pants during a trust fall",
  "A Dutch oven so bad it peels wallpaper",
  "Motorboating Mrs. Doubtfire",
  "Darth Vader force-choking your prostate",
  "Fisting a turkey on Thanksgiving and making eye contact with grandma",
  "The sound of a wet fart echoing through a silent church",
  "Mario going down the wrong pipe",
  "Being eskimo brothers with your dad",
  "A Costco-sized bucket of lube and a weekend with no plans",
  "Reverse birth",
  "Whacking off with a catcher's mitt",
  "Eating Fruit Loops out of a hooker's belly button",
  "Deepfake porn of yourself that's somehow better than you in real life",
  "The Rock gently cradling you like a baby while you cry",
  "Yoda riding you reverse cowgirl, he is",
  "A very aggressive bidet that's just a fire hose",
  "Two words: placenta omelette",
  "Hagrid's nine-pound meat wand",
  "Joking about 9/11 and getting a laugh",
  "Catching your reflection mid-wank and being disgusted",
  "Wiping with poison ivy",
  "Using your roommate's electric toothbrush and never telling them why",
  "Trying to suck your own dick and getting stuck",
  "A gerbil that's seen some shit",
  "Being the meat in a Golden Girls sandwich",
  "Accidentally calling your priest 'daddy'",
  "The noise a pug makes when it humps your leg",
  "Getting road head from someone with braces",
  "A colostomy bag that doubles as a wine skin",
  "Wario's unwashed taint",
  "Farting directly into a box fan pointed at your family",
  "An STI you don't have a name for yet",
  "Getting fingered by the Sorting Hat",
  "Post-nut clarity so intense you question your entire existence",
  "A used tampon found in the ball pit",
  "Dora the Explorer exploring some shit she shouldn't be",
  "Spider-Man shooting his web prematurely",
  "A weirdly arousing ASMR video of someone eating corn on the cob",
  "Jacking off with hand sanitizer and immediately regretting it",
  "Accidentally moaning during a dental cleaning",
  "A turd so long it touches the water before you pinch it off",
  "Sniffing the seat after spin class",
  "Jabba the Hutt in a thong",
  "Squeezing a blackhead the size of a Milk Dud",
  "Finding a pube in your teeth at dinner",
  "Elmo's surprisingly aggressive sex dungeon",
  "Getting pegged by Princess Leia while she chokes you with the chain",
  "The noise a suction cup dildo makes when it hits the shower wall",
  "Ron Weasley's ginger pubes tangled in the shower drain",
  "Walking in on your parents and your dad gives you a thumbs up",
  "An unsolicited dick pic from Pikachu",
  "Grandma's browser history: 47 tabs of hardcore porn",
  "A flesh-colored fanny pack that jiggles when you walk",
  "Hate-fucking your HOA president",
  "Taking a shit so massive you need to lie down afterward",
  "Competitive aggressive cuddling",
  "A trucker named Debbie who can crack walnuts with her ass cheeks",
  "A fart so hot it leaves a tan line",
  "The milk crust under a fat man's tit",
  "Two hobos wrestling over a soiled mattress",
  "Waking up spooning a traffic cone with no pants on",
  "Making unbroken eye contact while eating a banana at the urinal",
  "A very concerning rash shaped like Mickey Mouse",
  "Getting edged by the DMV line",
  "Elon Musk's Twitter feed printed and used as toilet paper",
  "Accidentally playing porn on the Bluetooth speaker at a baby shower",
  "A lap dance from Grimace",
  "Your dad's secret TikTok account",
  "The thing at the bottom of a public pool that nobody should touch",
  "A cum sock that can stand on its own",
  "Shart-based decision making",
  "Getting a handy from someone eating hot wings",
  "A haunted dildo that vibrates at 3 AM on its own",
  "Accidentally FaceTiming your boss while on the toilet",
  "Sucking the jelly out of a donut and making weird eye contact",
  "The crunchy texture of a cockroach in your burrito",
  "Getting pantsed at your kid's school play",
  "Using thoughts and prayers as lubricant",
  "A Dutch Rudder between bros",
  "That crusty washcloth in the shower that nobody claims ownership of",
  "Shitting yourself during a marathon and just keeping going",
  "A donkey show in a church basement",
  "Accidentally discovering your kink at Thanksgiving dinner",
  "Being kept as a sex pet by Amazonian women",
];

// Theme -> card arrays lookup
const themeDecks = {
  standard: { black: standardBlackCards, white: standardWhiteCards },
  scifi:    { black: scifiBlackCards,    white: scifiWhiteCards },
  fantasy:  { black: fantasyBlackCards,  white: fantasyWhiteCards },
  nostalgia:{ black: nostalgiaBlackCards, white: nostalgiaWhiteCards },
  horror:   { black: horrorBlackCards,   white: horrorWhiteCards },
  science:  { black: scienceBlackCards,  white: scienceWhiteCards },
};

// Build combined decks from selected themes
export function buildDeck(selectedThemes) {
  const ids = selectedThemes && selectedThemes.length > 0
    ? selectedThemes
    : ['standard'];

  let black = [];
  let white = [];
  for (const id of ids) {
    const deck = themeDecks[id];
    if (deck) {
      black = black.concat(deck.black);
      white = white.concat(deck.white);
    }
  }
  return { blackCards: black, whiteCards: white };
}
