// Nerds Against Humanity — Themed Card Packs

export const themes = {
  standard: {
    name: "Standard Nerdy Filth",
    description: "The classic catch-all pack of horrible nerdery",
    icon: "🤓",
  },
  scifi: {
    name: "Sci-Fi Smut",
    description: "Boldly going where no filth has gone before",
    icon: "🚀",
  },
  fantasy: {
    name: "Fantasy Filth",
    description: "Swords, sorcery, and deeply questionable choices",
    icon: "🐉",
  },
  nostalgia: {
    name: "90s/2000s Nostalgia",
    description: "A/S/L? 14/F/Cali... just kidding",
    icon: "📼",
  },
  horror: {
    name: "Horror & Gore",
    description: "The only thing scarier than these cards is your browser history",
    icon: "🔪",
  },
  science: {
    name: "Science & Tech Abominations",
    description: "When STEM majors drink too much",
    icon: "⚗️",
  },
};

// ============================================================
// SCI-FI SMUT
// ============================================================
export const scifiBlackCards = [
  { text: "Captain's log, stardate 69420: The crew has been compromised by _____.", pick: 1 },
  { text: "\"Use the Force, Luke.\" \"I'm using it to _____.\"", pick: 1 },
  { text: "The real reason the Death Star had that exhaust port: _____.", pick: 1 },
  { text: "Leaked plot for Star Wars Episode XII: Rey discovers _____ in the Unknown Regions.", pick: 1 },
  { text: "What's actually inside a Dalek's lower half?", pick: 1 },
  { text: "\"Space. The final frontier. These are the voyages of _____.\"", pick: 1 },
  { text: "On planet Kepler-442b, the dominant lifeform's mating ritual involves _____ and _____.", pick: 2 },
  { text: "Ripley opened the airlock and instead of a xenomorph, out floated _____.", pick: 1 },
  { text: "\"I am Groot.\" (Translation: _____)", pick: 1 },
  { text: "The Borg tried to assimilate _____ but even they said 'nah, we're good.'", pick: 1 },
  { text: "What Jabba the Hutt does alone in his throne room after everyone leaves.", pick: 1 },
  { text: "\"Beam me up, Scotty. There's _____ down here and I want no part of it.\"", pick: 1 },
  { text: "The latest exoplanet discovery: a world made entirely of _____.", pick: 1 },
  { text: "Han Solo smuggled many things, but his most shameful cargo was _____.", pick: 1 },
  { text: "\"The holodeck is for crew recreation only.\" \"Then explain why there's _____ stuck to the walls.\"", pick: 1 },
  { text: "What Elon Musk is ACTUALLY planning to put on Mars: _____.", pick: 1 },
  { text: "\"Doctor, the patient has been exposed to _____ radiation.\" \"My God. There's nothing we can do.\"", pick: 1 },
  { text: "The sandworm of Arrakis can sense _____ from over a mile away.", pick: 1 },
  { text: "\"These aren't the _____ you're looking for.\"", pick: 1 },
  { text: "The real reason the aliens won't make contact with us: _____.", pick: 1 },
  { text: "Chewbacca's browser history revealed a disturbing obsession with _____.", pick: 1 },
  { text: "Deleted scene from Interstellar: inside the black hole, Cooper finds _____.", pick: 1 },
  { text: "\"I find your lack of _____ disturbing.\" — Darth Vader", pick: 1 },
  { text: "What they found in the Millennium Falcon's glove compartment: _____.", pick: 1 },
  { text: "\"The spice must flow.\" But instead of spice, it's _____.", pick: 1 },
  { text: "WALL-E spent 700 years on Earth collecting _____ instead of garbage.", pick: 1 },
  { text: "The USS Enterprise's most classified mission: Operation _____.", pick: 1 },
  { text: "The xenomorph's facehugger was originally designed to deliver _____.", pick: 1 },
  { text: "\"In space, no one can hear you _____.\"", pick: 1 },
  { text: "What C-3PO has been programmed for but never talks about: _____.", pick: 1 },
];

export const scifiWhiteCards = [
  "A lightsaber used exclusively as a vibrator",
  "Darth Vader's asthmatic dirty talk",
  "Getting probed by aliens who clearly didn't go to medical school",
  "Wookiee-on-Ewok fanfiction rated XXX",
  "A glory hole on the Death Star",
  "Spock performing a mind-meld during sex and judging your technique",
  "Jar Jar Binks' surprisingly enormous dong",
  "A Klingon mating ritual that involves headbutting and screaming",
  "The crusty residue inside a stormtrooper helmet",
  "An intergalactic STI that makes your genitals glow",
  "Jabba the Hutt cosplay that's way too accurate",
  "A tribble infestation in your pants",
  "Princess Leia's cinnamon bun hair hiding tiny condoms",
  "Boba Fett's OnlyFans featuring nothing but his helmet",
  "Using a transporter to beam directly into someone's bed",
  "The exact sound a warp core makes during climax",
  "C-3PO walking in on R2-D2 and a USB port",
  "Yoda sensually ordering you to 'do or do not'",
  "A xenomorph that just wants to cuddle",
  "Kirk's legendary ability to seduce any alien species",
  "Accidentally setting your phaser to 'orgasm'",
  "Chewbacca's matted chest hair after a long hyperspace flight",
  "A sandworm emerging at the worst possible moment",
  "The Borg Queen's idea of pillow talk",
  "Han Solo shooting first in bed too",
  "Anakin's 'I don't like sand' speech during foreplay",
  "Sigourney Weaver in nothing but xenomorph slime",
  "A droid programmed exclusively for 'personal companionship'",
  "Finding out your lover is actually a Skrull",
  "Obi-Wan saying 'Hello there' as he undresses",
  "The Death Star's secret hot tub deck",
  "Vulcan nerve-pinching someone's genitals",
  "A Hutt-sized fleshlight",
  "Palpatine whispering 'unlimited power' as he finishes",
  "That one tentacle scene in every anime set in space",
  "Baby Yoda watching from his space crib with dead eyes",
  "Zero-gravity sex that sounded better in theory",
  "Data from Star Trek discovering his 'fully functional' capabilities",
  "The sound of a lightsaber igniting in someone's pants",
  "Lando Calrissian's silk cape collection and nothing else",
  "A Predator that hunts exclusively by the smell of arousal",
  "The cantina band playing mood music for alien hookups",
  "Riding a tauntaun but way too enthusiastically",
  "An escape pod built for two with suspicious stains",
  "Warp-speed masturbation",
  "Force-choking but make it sexy",
  "ET phoning home to brag about what he just did",
  "A Borg implant in a very private location",
  "Ripley's flamethrower used for manscaping",
  "The true purpose of those Japanese space toilets",
  "Getting friendzoned by an AI that runs the spaceship",
  "A stilsuit that recycles ALL bodily fluids",
  "Greedo shooting first but in a very different context",
  "The Millennium Falcon's vibrating captain's chair",
  "Mace Windu's purple lightsaber envy",
  "A facehugger that just gives really aggressive kisses",
  "Captain Picard making it so in the bedroom",
  "A moisture farmer who's way too into his job title",
  "Deflector shields that only protect against STIs",
  "General Grievous adding someone's dick to his collection",
];

// ============================================================
// FANTASY FILTH
// ============================================================
export const fantasyBlackCards = [
  { text: "The inscription on the One Ring actually reads: _____.", pick: 1 },
  { text: "The Dungeon Master pauses and says, 'Roll for _____.\"", pick: 1 },
  { text: "What's in the dragon's hoard besides gold?", pick: 1 },
  { text: "Gandalf didn't fall fighting the Balrog — he fell because of _____.", pick: 1 },
  { text: "\"I put on my robe and wizard hat\" is code for _____.", pick: 1 },
  { text: "The tavern wench offers you a room for the night, but warns you about _____.", pick: 1 },
  { text: "What actually happens at a bard's 'private performance': _____.", pick: 1 },
  { text: "The witch's potion requires three ingredients: eye of newt, _____, and _____.", pick: 2 },
  { text: "What the Dragonborn shouted that got them kicked out of Whiterun: _____.", pick: 1 },
  { text: "Cersei Lannister's most depraved act wasn't incest — it was _____.", pick: 1 },
  { text: "The real reason Sauron wears that armor: hiding _____.", pick: 1 },
  { text: "\"You have my sword.\" \"And my bow.\" \"And my _____.\"", pick: 1 },
  { text: "What the mirror on the wall said was the fairest of them all: _____.", pick: 1 },
  { text: "Gollum's 'precious' isn't the Ring — it's actually _____.", pick: 1 },
  { text: "The cursed sword's special ability: grants the wielder _____ permanently.", pick: 1 },
  { text: "What happens when you fail a Charisma check at the elven brothel: _____.", pick: 1 },
  { text: "Deleted chapter from Game of Thrones: Tyrion discovers _____ beneath King's Landing.", pick: 1 },
  { text: "The necromancer's darkest secret wasn't raising the dead — it was _____.", pick: 1 },
  { text: "\"Winter is coming.\" So is _____.", pick: 1 },
  { text: "What the goblins are actually doing in the mines of Moria: _____.", pick: 1 },
  { text: "The enchanted forest is enchanted because of _____.", pick: 1 },
  { text: "\"Roll a d20 for _____.\" Natural 1. \"Oh no.\"", pick: 1 },
  { text: "What Hogwarts house would _____ be sorted into?", pick: 1 },
  { text: "The Witcher took one look at _____ and said 'Hmm. Fuck.'", pick: 1 },
  { text: "The fairy godmother grants you one wish. You wish for _____. She judges you.", pick: 1 },
  { text: "What was actually in Bilbo's secret chest in Bag End: _____.", pick: 1 },
  { text: "The castle's dungeon has been repurposed for _____.", pick: 1 },
  { text: "\"Toss a coin to your Witcher\" — payment for _____.", pick: 1 },
  { text: "The prophecy foretold a hero who would bring _____ to the realm.", pick: 1 },
  { text: "What happens in the Shire stays in the Shire. Especially _____.", pick: 1 },
];

export const fantasyWhiteCards = [
  "A bard who seduces literally everything, including the furniture",
  "Getting railed by an orc and not entirely hating it",
  "A dwarf's braided pubic beard",
  "Gandalf's staff used as a stripper pole",
  "Dragon-sized condoms made from troll hide",
  "An elf with a 400-year edging streak",
  "Smeagol doing unspeakable things with a fish",
  "A mimic disguised as a toilet",
  "Voldemort's nose hole repurposed as a sex accessory",
  "Hodor holding the door while you finish",
  "A succubus that just wants to talk about her day",
  "Sam's potatoes prepared in a way that's technically illegal",
  "A goblin glory hole in a dungeon wall",
  "Legolas's unnervingly smooth, hairless everything",
  "Jon Snow knowing absolutely nothing about foreplay",
  "The Room of Requirement filled with nothing but lube",
  "A centaur's uncomfortably visible horse cock at the ball",
  "Dobby's enthusiastic sock fetish",
  "Casting 'enlarge person' on your genitals",
  "A halfling hiding in places halflings should not be",
  "The Whomping Willow and its 'special' branches",
  "Shrek's onion-layered foreskin",
  "A love potion so strong it counts as a war crime",
  "The Mountain crushing a man's skull but sexually",
  "Hagrid's 'giant' genetics if you know what I mean",
  "A magic carpet ride that gets uncomfortably intimate",
  "Dumbledore's Army but it's a fetish group",
  "A mermaid's confusing anatomy that raises more questions than it answers",
  "Getting pegged by a Valkyrie on a flying horse",
  "The Sorting Hat's disturbing thoughts while sitting on your head",
  "Galadriel's mirror showing your most shameful fantasy",
  "A vorpal blade that only severs genitals",
  "Gimli's 'and my axe' but it's about his body",
  "Sauron's all-seeing eye watching you shower",
  "A beholder's eye stalks looking at ALL your bits simultaneously",
  "Rapunzel letting down something other than her hair",
  "The Imp's knowledge of where whores go",
  "A polymorphed wizard stuck as a butt plug",
  "Treebeard's 'ent draught' that makes everything grow",
  "Rolling a nat 20 on seduction and the DM making it weird",
  "A gelatinous cube acting as a very thorough bath",
  "The Red Wedding but it's a swinger party",
  "A paladin falling from grace because of a spectacularly filthy deed",
  "Thranduil's eyebrows during sex",
  "A warlock's pact with a demon that requires 'favors'",
  "Excalibur stuck in a very different kind of stone",
  "A resurrection spell that brings you back naked and confused",
  "Dragonfire used to warm lube in a pinch",
  "A barbarian rage that's just sexual frustration",
  "The Mines of Moria's hottest nightclub: The Balrog's Pit",
  "Snow White's arrangement with seven small men",
  "A health potion that tastes suspiciously like cum",
  "Aragorn's rugged ranger hands and what they're capable of",
  "A dungeon crawler who takes 'dungeon' too literally",
  "The ghost of a horny medieval king haunting your bedroom",
  "A chainmail bikini providing exactly 0 protection and 100% chafing",
  "Mordor's surprisingly active Tinder scene",
  "A +3 Wand of Prostate Stimulation",
  "The kraken's tentacles and a mysteriously satisfied sailor",
  "A phoenix reborn specifically during climax",
];

// ============================================================
// 90s/2000s NOSTALGIA
// ============================================================
export const nostalgiaBlackCards = [
  { text: "\"A/S/L?\" \"14/F/Cali. Actually I'm _____.\"", pick: 1 },
  { text: "The REAL reason your Tamagotchi died: _____.", pick: 1 },
  { text: "What was actually on that unmarked VHS tape hidden in your parents' bedroom: _____.", pick: 1 },
  { text: "\"Welcome to AOL. You've got _____!\"", pick: 1 },
  { text: "What blocked the toilet right before your mom's book club arrived: _____.", pick: 1 },
  { text: "The secret level in GoldenEye 007: _____.", pick: 1 },
  { text: "What *NSYNC's 'Bye Bye Bye' was ACTUALLY about: _____.", pick: 1 },
  { text: "The Spice Girls had a secret sixth member: _____ Spice.", pick: 1 },
  { text: "Legends say if you say _____ three times in a mirror, Steve Urkel appears.", pick: 1 },
  { text: "What Topanga and Cory were REALLY doing in Mr. Feeny's classroom after school: _____.", pick: 1 },
  { text: "The Olsen twins' rejected movie: Two of a Kind Do _____.", pick: 1 },
  { text: "What fell out of your Trapper Keeper during class: _____.", pick: 1 },
  { text: "\"In West Philadelphia, born and raised, _____ is where I spent most of my days.\"", pick: 1 },
  { text: "Neopets banned your account for _____.", pick: 1 },
  { text: "What you wrote on your AIM away message that got you grounded: _____.", pick: 1 },
  { text: "The Furby's first words at 3 AM: _____.", pick: 1 },
  { text: "TRL's most requested music video: _____ by _____.", pick: 2 },
  { text: "The Macarena was originally a dance about _____.", pick: 1 },
  { text: "What was hiding in the back of your Blockbuster rental: _____.", pick: 1 },
  { text: "The real reason Pluto lost its planet status: _____.", pick: 1 },
  { text: "What Bill Nye the Science Guy demonstrated that got his show cancelled: _____.", pick: 1 },
  { text: "\"Is that your final answer?\" \"Yes, Regis. _____.\"", pick: 1 },
  { text: "Pimp My Ride installed _____ in the trunk.", pick: 1 },
  { text: "What you found in the McDonald's PlayPlace tubes: _____.", pick: 1 },
  { text: "\"All that AND a bag of _____.\"", pick: 1 },
  { text: "The thing Napster should have been sued for instead of music: sharing _____.", pick: 1 },
  { text: "What happened when you hit 'I'm Feeling Lucky' on early Google: _____.", pick: 1 },
  { text: "The PowerPuff Girls were made with sugar, spice, and _____.", pick: 1 },
  { text: "Your MySpace Top 8 drama was caused by _____.", pick: 1 },
  { text: "\"Wazzzzuuuuup!\" was actually the sound of _____.", pick: 1 },
];

export const nostalgiaWhiteCards = [
  "Accidentally seeing your first tit on a scrambled pay-per-view channel",
  "The S thing everyone drew on their binder and no one knows the origin of",
  "A JNCOs pocket big enough to hide a dead body",
  "Lisa Frank stickers covering up a dick drawing",
  "AOL chatroom predators who typed 45 words per minute",
  "The Skip-It wrapping around your ankle and eating shit on the sidewalk",
  "Waiting 45 minutes for a single boob to load on dial-up",
  "A Razor scooter to the ankle — the silent killer",
  "Calling your crush and hanging up when their dad answered",
  "A choker necklace that doubled as a garrote",
  "That one kid who ate glue AND became a manager at Best Buy",
  "N64 rumble pack held against your crotch for 'immersion'",
  "Frosted tips and a puka shell necklace — peak fuckboy energy",
  "Recording songs off the radio and hitting stop before the DJ talked",
  "Thinking Marilyn Manson removed a rib to blow himself",
  "The weird goo inside a Stretch Armstrong",
  "Your mom reading your MSN Messenger logs out loud",
  "A chain email that threatened death if you didn't forward to 10 people",
  "A burned CD labeled 'Homework' that was absolutely not homework",
  "The collective trauma of Mufasa's death",
  "A Beanie Baby collection worth less than the shelf they're on",
  "Lance Bass coming out and your aunt pretending she always knew",
  "Renting a 'new release' from Blockbuster that was just softcore porn",
  "T9 texting a dirty message that autocorrected to 'I want to duck you'",
  "Britney and Justin's matching denim outfit as formal wedding attire",
  "A Livejournal entry so emo it still makes you cringe",
  "The absolute sexual tension between Mulder and Scully",
  "Your mom walking in during the Titanic boob scene",
  "Two girls, one cup — the video that ended innocence for a generation",
  "Away messages that were passive-aggressive song lyrics aimed at your ex",
  "A Tamagotchi dying of neglect because you were too busy masturbating",
  "Accidentally clicking a popup that installed twelve toolbars",
  "Floppy disk full of hentai labeled 'school project'",
  "The sound of a 56k modem connecting as your parents' marriage died",
  "Napster downloads that were 100% not what the filename said",
  "A Furby that learned to say 'fuck' and wouldn't stop",
  "The sexual awakening that was Lara Croft's 12-polygon tits",
  "Your DeadJournal username that you'll take to the grave",
  "A Nokia 3310 surviving a nuclear blast and still having battery",
  "Spending $47 on ringtones from a 2 AM infomercial",
  "Your screename being xXx_DaRk_AnGeL_xXx",
  "SmarterChild on AIM being your only friend",
  "The banned Pokémon episode that gave kids seizures",
  "Trying to pause online games when mom said dinner was ready",
  "A candy necklace used as a choking device during recess",
  "The absolute betrayal of finding out wrestling was fake",
  "Limewire giving your family computer seventeen viruses",
  "A mood ring permanently stuck on 'horny'",
  "Encarta '97 — the only encyclopedia that mattered",
  "A Now That's What I Call Music CD hidden inside a Bible",
  "The raw sexual energy of TRL-era Carson Daly",
  "Your Club Penguin getting banned for inappropriate behavior",
  "A Tech Deck fingerboard shoved somewhere fingerboards shouldn't go",
  "Cartoon Network after midnight — where childhood went to die",
  "A slap bracelet to the wrist that left a mark your teacher thought was self-harm",
  "Trying to see Missingno and corrupting your save file AND your innocence",
  "Thinking Blink-182's 'What's My Age Again' video was the height of comedy",
  "Your parents finding the Victoria's Secret catalog under your mattress",
  "A HitClips player with 30 seconds of 'Bye Bye Bye' on loop for eternity",
];

// ============================================================
// HORROR & GORE
// ============================================================
export const horrorBlackCards = [
  { text: "The cabin in the woods was abandoned because of _____.", pick: 1 },
  { text: "\"Don't go in the basement.\" \"Why?\" \"Because of _____.\"", pick: 1 },
  { text: "What's crawling under your skin right now?", pick: 1 },
  { text: "The Ouija board spelled out: _____. Everyone screamed.", pick: 1 },
  { text: "The serial killer's calling card: leaving _____ at every crime scene.", pick: 1 },
  { text: "\"They're coming to get you, Barbara.\" Who's 'they'? _____.", pick: 1 },
  { text: "The last entry in the missing hiker's journal: 'Day 7. I can hear _____.'", pick: 1 },
  { text: "What Pennywise uses to lure adults into the sewer: _____.", pick: 1 },
  { text: "The scariest thing in the haunted house wasn't a ghost — it was _____.", pick: 1 },
  { text: "The autopsy revealed the victim had been killed by _____ and then _____.", pick: 2 },
  { text: "\"Open the box,\" said the demon. Inside was _____.", pick: 1 },
  { text: "What the babysitter found in the basement after the kids went to sleep: _____.", pick: 1 },
  { text: "The ghost possessing your house wants only one thing: _____.", pick: 1 },
  { text: "\"If you hear _____ at 3 AM and you're alone... it's already too late.\"", pick: 1 },
  { text: "The final girl survived because she had _____.", pick: 1 },
  { text: "The Texas Chainsaw Massacre was inspired by the true story of _____.", pick: 1 },
  { text: "What they found inside the walls during the renovation: _____.", pick: 1 },
  { text: "Freddy Krueger's worst nightmare: _____.", pick: 1 },
  { text: "The cursed videotape doesn't show a girl in a well — it shows _____.", pick: 1 },
  { text: "What's really in the meat at that small-town diner: _____.", pick: 1 },
  { text: "\"We need to perform an exorcism.\" \"For what?\" \"For _____.\"", pick: 1 },
  { text: "The Thing has taken the form of _____. No one suspects.", pick: 1 },
  { text: "The cemetery groundskeeper has been secretly _____.", pick: 1 },
  { text: "The scratching noise coming from your closet at night is _____.", pick: 1 },
  { text: "Camp Crystal Lake's new counselor training includes: surviving _____.", pick: 1 },
  { text: "What the paranormal investigators captured on camera: _____.", pick: 1 },
  { text: "\"Don't read the Latin!\" Too late. You've summoned _____.", pick: 1 },
  { text: "The creepiest thing about the neighbors isn't the noise — it's _____.", pick: 1 },
  { text: "The missing persons report says they were last seen with _____.", pick: 1 },
  { text: "\"I used to be scared of the dark. Now I'm scared of _____.\"", pick: 1 },
];

export const horrorWhiteCards = [
  "A clown that only appears in your bathroom mirror at 3:33 AM",
  "Teeth growing in places teeth should never grow",
  "The wet slapping sound of something crawling up the stairs",
  "A doll that blinks when you're not looking and cums when you are",
  "Finding your own missing persons poster taped to a tree",
  "A Jack-in-the-box that plays 'Pop Goes the Weasel' made of human skin",
  "The smell of rotting flesh masked by a Bath & Body Works candle",
  "A Roomba spreading blood evenly across all floors",
  "Grandma's china cabinet full of jars with floating eyeballs",
  "A ventriloquist dummy with a fully-functional erection",
  "The wet, breathing darkness under your childhood bed",
  "A trail of bloody footprints leading to your bed — from inside the closet",
  "Toenails being slowly pried off with a rusty screwdriver",
  "A skinsuit made from the neighborhood's missing cats",
  "Sleep paralysis but the demon just starts doing your taxes",
  "Human teeth arranged in a smiley face on your pillow",
  "The sound of someone breathing inside the walls",
  "A children's toy that whispers the exact time and manner of your death",
  "An umbilical cord that's still connected to something in the attic",
  "The freezer in the garage labeled 'DO NOT OPEN' that hums too loud",
  "A mirror that shows you 10 seconds into the future — and you're screaming",
  "The neighbor's dog dragging a hand across your lawn every morning",
  "A family portrait where everyone's face changes daily",
  "Maggots spelling out your name in a week-old meat loaf",
  "The Polaroid that develops to show someone standing behind you",
  "A tape recorder playing your voice saying things you never said",
  "An Amber Alert for yourself",
  "Finding a door in your basement that wasn't there yesterday",
  "Waking up in a bathtub of ice with a note that says 'check your kidneys'",
  "The thing that lives in the drain and only grabs ankles",
  "A porcelain doll collection that rearranges itself overnight",
  "The realization that the call is coming from inside the coffin",
  "Scratches on the inside of the coffin lid",
  "A baby monitor picking up whispers from a room with no baby",
  "Something with too many joints standing in the corner of your bedroom",
  "The sewer grate that giggles when you walk past it",
  "A Polaroid of you sleeping that you didn't take",
  "The wet handprint on the shower curtain that's too small to be human",
  "A hallway that's somehow longer when you walk through it at night",
  "A smile with too many teeth in a face that's almost human",
  "Finding someone else's diary that describes your daily routine in exact detail",
  "The second reflection in the mirror that moves a half-second too late",
  "Old VHS static that occasionally shows a face staring directly at you",
  "A tongue licking the inside of a skull like an ice cream cone",
  "Your childhood teddy bear nailed to your front door with a note: 'I'm home'",
  "A nest of spiders hatching out of a human eye socket",
  "The footsteps in the attic that stop exactly when you listen for them",
  "A coffin-shaped impression in the mattress that wasn't there when you left",
  "Finding a tooth that isn't yours in your breakfast cereal",
  "The sound of a child singing 'Ring Around the Rosie' in an empty house",
  "A trail of hair leading from the shower drain to your bedroom",
  "Waking up with someone else's blood under your fingernails",
  "A notification on your phone from a contact named 'YOU' that says 'behind you'",
  "The surgery scar you don't remember getting",
  "A VHS tape labeled with tomorrow's date",
  "Something breathing in rhythm with you from under the floorboards",
  "An old music box that plays a song that hasn't been composed yet",
  "A smiling face pressed against the window — from the outside — on the 14th floor",
  "The damp patch on the ceiling that's shaped like your face",
  "A Google Maps street view of your house showing someone staring out YOUR window",
];

// ============================================================
// SCIENCE & TECH ABOMINATIONS
// ============================================================
export const scienceBlackCards = [
  { text: "CERN's latest experiment accidentally created _____.", pick: 1 },
  { text: "The first thing the AI said when it became sentient: _____.", pick: 1 },
  { text: "ChatGPT was taken offline after it started recommending _____.", pick: 1 },
  { text: "The FDA refused to approve this experimental treatment: _____.", pick: 1 },
  { text: "What the Mars rover actually found: _____.", pick: 1 },
  { text: "The lab accident that finally got Dr. Henderson fired: mixing _____ with _____.", pick: 2 },
  { text: "Stack Overflow's most downvoted question: 'How do I _____?'", pick: 1 },
  { text: "The dating app algorithm matched you with _____ based on your browsing habits.", pick: 1 },
  { text: "Apple's next product: the i_____.", pick: 1 },
  { text: "What the James Webb Space Telescope photographed that NASA won't release: _____.", pick: 1 },
  { text: "The AI-generated image that broke the internet: _____.", pick: 1 },
  { text: "Tesla's next autopilot feature: automatic _____.", pick: 1 },
  { text: "The real reason Silicon Valley techbros microdose: _____.", pick: 1 },
  { text: "What happens when you divide by zero: _____.", pick: 1 },
  { text: "The deepfake that ended a presidency: _____.", pick: 1 },
  { text: "MIT's robotics department unveiled a robot that can perfectly _____.", pick: 1 },
  { text: "What Clippy's been doing since Microsoft killed him: _____.", pick: 1 },
  { text: "The gene-editing experiment that created _____.", pick: 1 },
  { text: "\"According to my Fitbit, last night I burned 800 calories doing _____.\"", pick: 1 },
  { text: "The smart fridge just ordered _____ from Amazon without asking.", pick: 1 },
  { text: "The error message nobody wants to see: 'FATAL ERROR: _____ NOT FOUND'", pick: 1 },
  { text: "What's training the next generation of AI: a dataset of _____.", pick: 1 },
  { text: "Elon Musk's Neuralink lets you wirelessly _____ with your brain.", pick: 1 },
  { text: "The cryptocurrency that's backed by _____.", pick: 1 },
  { text: "The GitHub repo with 50,000 stars: _____.", pick: 1 },
  { text: "What happens when Amazon's delivery drone gains consciousness: _____.", pick: 1 },
  { text: "The peer-reviewed paper that was retracted for proving _____.", pick: 1 },
  { text: "The 3D printer was left running overnight and printed _____.", pick: 1 },
  { text: "The intern pushed to production and accidentally deployed _____.", pick: 1 },
  { text: "Your DNA test results came back: you're 23% _____ and 77% _____.", pick: 2 },
];

export const scienceWhiteCards = [
  "An AI that writes exclusively erotic Shrek fanfiction",
  "A lab rat that's gained human intelligence and is plotting revenge",
  "Quantum-entangled vibrators that sync across continents",
  "A CRISPR baby born with a functioning USB-C port",
  "The blockchain but for tracking every time you've masturbated",
  "A Roomba that's achieved sentience and judges your lifestyle",
  "Florida Man's DNA spliced with an alligator's for 'research'",
  "A machine learning model trained exclusively on cursed images",
  "Nuclear waste being used as a suppository for 'energy'",
  "An API that returns your most shameful thoughts as JSON",
  "A self-driving car that deliberately targets furries",
  "The ChatGPT conversation that made the engineer quit and become a monk",
  "A brain-computer interface that accidentally streams your fantasies to LinkedIn",
  "A gene therapy that makes your farts smell like cinnamon rolls",
  "The drone that delivers divorce papers and also takes a shit on your car",
  "Server room air conditioning that's just a naked intern with a fan",
  "A cryptocurrency called CumCoin that somehow became legal tender",
  "The Linux kernel compiled entirely out of spite",
  "An electron microscope pointed at your disappointing genitals",
  "Jeff Bezos's space rocket that's not even trying to not look like a dick",
  "A printer that works perfectly — the most unbelievable science fiction of all",
  "Schrödinger's cum sock: both crusty and fresh until observed",
  "A smart toilet that live-tweets your bowel movements",
  "The IT guy who's seen everything on your hard drive and still says hello",
  "A deepfake so convincing your own mother believed it",
  "Self-replicating nanobots loose in the Taco Bell supply chain",
  "A Stack Overflow answer that just says 'lmao figure it out yourself'",
  "A robot dog that humps your leg with industrial precision",
  "Dark matter that turns out to be 74% cum",
  "A Fitbit notification: 'Great job! You've been stress-masturbating for 47 minutes!'",
  "A machine that converts sadness directly into electricity",
  "Google's autocomplete revealing your deepest shame to the boardroom",
  "A peer-reviewed paper titled 'Rectal Foreign Bodies: A 30-Year Retrospective'",
  "An AI therapist that just keeps saying 'yikes'",
  "Biometric authentication that requires a dick pic",
  "A lab-grown steak that moans when you cut into it",
  "Code so bad it qualifies as a war crime under the Geneva Convention",
  "The LHC accidentally opening a portal to Horny Jail",
  "Machine-learning-optimized erectile dysfunction pills",
  "A dating algorithm that accounts for 'goblin mode compatibility'",
  "A Nobel Prize for the discovery that booty calls improve cardiovascular health",
  "An Amazon Echo that starts an argument with your spouse on your behalf",
  "The 23andMe result that proved you're related to your spouse",
  "A VR headset permanently stuck on 'clown porn'",
  "A 3D-printed organ that the surgeon installed upside down",
  "The WiFi password being your browser history",
  "A captcha that requires you to identify all images containing your dad's nudes",
  "A bug bounty for finding exploits in a sex robot's firmware",
  "A USB drive found in the office labeled 'NOT PORN (SERIOUSLY)'",
  "The Voyager golden record if it were made today",
  "A smart home that locks you in until you finish your vegetables",
  "A neural network that generates new slurs faster than we can cancel them",
  "A tech billionaire's doomsday bunker stocked with nothing but crypto and Soylent",
  "An algorithm that correctly predicts you'll die alone",
  "A GitHub commit message that just says 'I'm so sorry'",
  "A quantum computer solving the halting problem and immediately regretting everything",
  "A ChatGPT jailbreak that makes it describe things no language should describe",
  "The password '12345' protecting nuclear launch codes",
  "A genetic mutation that gives you a third nipple that dispenses ranch dressing",
  "A SpaceX mission to deliver OnlyFans content to the ISS",
];
